@LocalVariable_HostAddress = https://localhost:7237

GET {{LocalVariable_HostAddress}}/api/videogame/
Accept: application/json
###

POST {{LocalVariable_HostAddress}}/api/videogame
Content-Type: application/json

{   
    "name": "Nuevo - cambio",
    "description": "Jejej"
}
###

@id=3
DELETE {{LocalVariable_HostAddress}}/api/videogame/{{id}}
Content-Type: application/json
###

@id=3
GET {{LocalVariable_HostAddress}}/api/videogame/{{id}}
Content-Type: application/json
###

@id=3
PUT {{LocalVariable_HostAddress}}/api/videogame/{{id}}
Content-Type: application/json

{
  "name": "Este es",
  "description": "Lo quiero"
}
###
